/*
 * $Id: GTCertTokenResponse.java 169 2011-03-03 18:45:00Z ahto.truu $
 *
 *
 *
 * Copyright 2008-2011 GuardTime AS
 *
 * This file is part of the GuardTime client SDK.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.guardtime.tsp;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;

import com.guardtime.asn1.Asn1FormatException;
import com.guardtime.asn1.CertToken;
import com.guardtime.asn1.CertTokenResponse;



/**
 * Extending service response wrapper.
 * <p>
 * Timestamping service response is what the extending service sends in response
 * to extending request. This response contains status and error codes, and may
 * contain data needed for timestamp extending, if that data was generated by
 * the service.
 * <p>
 * To extend timestamp, use
 * {@link com.guardtime.tsp.GTTimestamp#extend(GTCertTokenResponse)} method.
 *
 * @since 0.4
 */
public class GTCertTokenResponse
extends Response {
	private CertToken token;



	/**
	 * Creates a new extension response object from the given byte array containing
	 * DER-encoded extending service response.
	 *
	 * @param b DER-encoded extending service response.
	 *
	 * @return extension response object.
	 *
	 * @throws GTException if service response has invalid format.
	 */
	public static GTCertTokenResponse getInstance(byte[] b)
	throws GTException {
		if (b == null) {
			throw new IllegalArgumentException("invalid response data: null");
		}

		return getInstance(b, 0, b.length);
	}

	/**
	 * Creates a new extension response object from part of the given byte array
	 * containing DER-encoded extending service response.
	 *
	 * @param b byte array containing DER-encoded extending service response.
	 * @param offset offset to start reading service response from.
	 * @param length service response length.
	 *
	 * @return extension response object.
	 *
	 * @throws GTException if service response has invalid format.
	 */
	public static GTCertTokenResponse getInstance(byte[] b, int offset, int length)
	throws GTException {
		if (b == null) {
			throw new IllegalArgumentException("invalid response data: null");
		}

		try {
			ByteArrayInputStream in = new ByteArrayInputStream(b, offset, length);
			return getInstance(in);
		} catch (IOException e) {
			throw new GTException("response has invalid format", e);
		}
	}

	/**
	 * Reads a new extension response object from the given input stream.
	 *
	 * @param in input stream containing DER-encoded extending service
	 * 			response.
	 *
	 * @return extension response object.
	 *
	 * @throws GTException if service response has invalid format.
	 * @throws IOException if stream reading error occurs.
	 */
	public static GTCertTokenResponse getInstance(InputStream in)
	throws IOException, GTException {
		if (in == null) {
			throw new IllegalArgumentException("invalid response stream: null");
		}

		try {
			CertTokenResponse response = CertTokenResponse.getInstance(in);
			return new GTCertTokenResponse(response);
		} catch (Asn1FormatException e) {
			throw new GTException("response has invalid format", e);
		}
	}



	/**
	 * Returns cert token, if any, contained in this response.
	 * <p>
	 * Used by {@code GTTimestamp#extend(GTCertTokenResponse)} method.
	 *
	 * @return generated cert token, or {@code null}.
	 */
	CertToken getToken() {
		return token;
	}



	/**
	 * Class constructor.
	 * <p>
	 * Called by {@code getInstance} methods.
	 *
	 * @throws GTException if response internal structure has invalid format.
	 */
	private GTCertTokenResponse(CertTokenResponse response) {
		super(response.getStatusInfo().getStatusCode(), response.getStatusInfo().getFailCode());
		token = response.getToken();
	}

}
